from .umea_energi import UmeaEnergi
from .solor_bioenergi import SolorBioenergi
from .skelleftea_kraft import SkellefteaKraft
from .harnosand_energi_och_miljo import HarnosandEnergiOchMiljo
from .similar_template_crawlers_reports import SimilarTemplateCrawlersReports
from .affarsverken import Affarsverken
from .nevel import Nevel
from .eforsyning import Eforsyning
from .sollentuna_energi_och_miljo import SollentunaEnergiOchMiljo
from .oresundskraft import Oresundskraft
from .vantaan_energi import VantaanEnergi
from .tekniska_verken import TekniskaVerken
from .goteborg_energi import GoteborgEnergi
from .hofor import Hofor
from .vattenfall_v1 import VattenfallV1
from .vattenfall_v1_v2 import Vattenfall
from .vattenfall_heating import VattenfallHeating
from .kalmar_energi import KalmarEnergi